services:
  - type: web
    name: searxng
    env: python
    repo: https://github.com/theEndless11/searxng
    branch: master
    buildCommand: |
      pip install -r requirements.txt
    startCommand: ./manage services start
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
